### ISSUE TITLE
setting cs_option

### ISSUE THREAD

**Issue by aep** [capstone-rust/capstone-rs#12]
how would i set a cs_option? the api doesnt seem to be exposed

**Comment by tathanhdinh** [comment]
I think it is implemented in [`capstone.rs`](https://github.com/richo/capstone-rs/blob/master/src/capstone.rs#L82), but the method is not set as public yet.

**Comment by tmfink** [comment]
The `Capstone` struct now has public methods like `set_mode()`, `set_detail()`, and `set_extra_mode()`.
