### ISSUE TITLE
Cannot build capstone-rs

### ISSUE THREAD

**Issue by 0xd34d10cc** [capstone-rust/capstone-rs#15]
Cargo.toml:
```
...
[dependencies]
capstone = { git = "https://github.com/capstone-rust/capstone-rs" }
...
```
cargo build:
```
    Updating git repository `https://github.com/capstone-rust/capstone-rs`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching version `^0.3.0` found for package `capstone-sys` (required by `c
apstone`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.5.0, 0.4.0, 0.2.0, ...
```
Looks like it happens because capstone-sys 0.3.0 was [yanked](https://crates.io/crates/capstone-sys/0.3.0) but capstone-rs still [depends](https://github.com/capstone-rust/capstone-rs/blob/master/Cargo.toml#L12) on it.

**Comment by richo-stripe** [comment]
Hey, I'm publishing a new release now that should fix this issue for you. Sorry for the brokenness :(

**Comment by tmfink** [comment]
I uploaded version 0.1.0 to crates.io, which should fix the problem.
