### ISSUE TITLE
make build reproducible for capstone_sys

### ISSUE THREAD

**Issue by chenhdc** [capstone-rust/capstone-rs#152]
Hi, we found libcapstone_sys.rlib varies from filesystem readdir order.  Probably from the read_dir in  https://github.com/capstone-rust/capstone-rs/blob/7c9a51f6eb81709cde1de7f7498a0e16f29bd852/capstone-sys/build.rs#L74.  fs::read_dir()'s behavior is platform-specific.  
We found [https://github.com/gyscos/zstd-rs/pull/162](url) resolves a similar issue in another lib. Please make build reproducible for capstone_sys.

**Comment by tmfink** [comment]
Fixed by #153

**Comment by chenhdc** [comment]
@tmfink  when fix this issue， could publish a new release?

**Comment by tmfink** [comment]
> @tmfink when fix this issue， could publish a new release?

capstone-sys v0.16.0 and capstone v0.12.0 were just published
