### ISSUE TITLE
X86OpMem methods are private

### ISSUE THREAD

**Issue by m101** [capstone-rust/capstone-rs#33]
Hi,

X86OpMem methods are private, these makes it impossible to access the different attributes.

Here is a patch
[private.txt](https://github.com/capstone-rust/capstone-rs/files/1957049/private.txt)

**Comment by tmfink** [comment]
Thank you for the report!

Next time, you can make a change in your own fork and file a Pull Request.

https://help.github.com/articles/creating-a-pull-request/

**Comment by m101** [comment]
Thanks for the fast patch!

Oh right, ok I'll do that next time.

**Comment by tmfink** [comment]
Fixed with #34

**Comment by AZWN** [comment]
Would you mind creating a new version on crates.io? Currently the dependency is defined as below, but I do not really like to have a github revision as version:

```
capstone = { git = "https://github.com/capstone-rust/capstone-rs.git", rev = "dc10578aa27414afc93f0a87959b2f0c22dc66c3" }
```

**Comment by tmfink** [comment]
@AZWN release 0.4.0 is now available with many bug fixes, including this one.
