### ISSUE TITLE
Support new architectures

### ISSUE THREAD

**Issue by emoon** [capstone-rust/capstone-rs#52]
Capstone supports a bunch of new archs that isn't supported by capstone-rs yet. Any plans to add support for them?

**Comment by tmfink** [comment]
Once https://github.com/capstone-rust/capstone-sys/pull/31 goes through, we can add the new platforms. It shouldn't be too hard.

**Comment by tmfink** [comment]
Parent tracking issue: https://github.com/aquynh/capstone/issues/1315
