### ISSUE TITLE
index() method for ArmOpMem returns wrong type

### ISSUE THREAD

**Issue by xcoldhandsx** [capstone-rust/capstone-rs#53]
Hello! It seems to me, that index() method for ArmOpMem returns the wrong type. Now it looks like:
```
 /// Base register
    pub fn base(&self) -> RegId {
        RegId(self.0.base as RegIdInt)
    }
 /// Index value
    pub fn index(&self) -> u32 {
        self.0.index as u32
}
```

I think, it should return RegId as base() method do. Here my debug disassembly output that proves my theory:

0x0: str r2, [r3, r4]
    insn id:     212
    bytes:       [4, 32, 131, 231]
    read regs:   
    write regs:  
    insn groups: arm
    operands: 2
        ArmOperand(ArmOperand { vector_index: None, subtracted: false, shift: Invalid, op_type: Reg(RegId(68)) })
        ArmOperand(ArmOperand { vector_index: None, subtracted: false, shift: Invalid, op_type: Mem(ArmOpMem(arm_op_mem { base: 69, index: 70, scale: 1, disp: 0 })) })

**Comment by tmfink** [comment]
Nice catch! Makes sense since `ARM_REG_R4: u32 = 70`.
