### ISSUE TITLE
public the Insn.detail() method

### ISSUE THREAD

**Issue by lj94093** [capstone-rust/capstone-rs#99]
For some reason I need to get the operand type of a instruction.
But I find that `Insn.detail()` is a private method.
```
pub(crate) unsafe fn detail(&self, arch: Arch) -> InsnDetail {
    InsnDetail(&*self.insn.detail, arch)
}
```
Is there some reason necessarily to set the `detail()` to `pub(crate)`?Or maybe I have to use the `capstone-sys` directly?

**Comment by tmfink** [comment]
You can get an instance of `InsnDetail` by calling `Capstone::insn_detail()`. Then, you can get the architecture-specific detail (like operands) by calling the `.arch_detail()` method. For details, see the `demo` example:

https://github.com/capstone-rust/capstone-rs/blob/e294314c42e0572e09d987744f77e60a0780073a/capstone-rs/examples/demo.rs#L38-L40

**Comment by tmfink** [comment]
I should probably add "back references" to the types that explain how to get an instance of that type.
